language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
install:
    - pip uninstall setuptools -y
    - python bootstrap.py
    - ./bin/buildout install scripts crate test
script:
    - ./bin/test
notifications:
    email: false
sudo: false
