language: python
cache: pip
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - nightly

before_install:
    - pip install --upgrade setuptools

install:
    - python bootstrap.py
    - bin/buildout install scripts crate test

script:
    - bin/coverage run bin/test

after_success:
    - PATH=$PATH:bin/ bin/codecov  # codecov executes coverage which needs to be in $PATH
    - pip install coveralls
    - coveralls

notifications:
    email: false

sudo: false
addons:
  apt:
    packages:
        - oracle-java8-installer

matrix:
    allow_failures:
        - python: nightly
