language: python
cache: pip
python:
    - 3.4
    - 3.5
    - 3.6
    - pypy3
    - nightly

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get update
  - sudo apt-get install -y openjdk-12-jdk

install:
    - pip install ".[test]" urllib3==1.21.1 flake8==2.5.1
    - pip install coverage flake8

script:
    - flake8 crate/crash
    - coverage run -m unittest -v

after_success:
    - PATH=$PATH:bin/ bin/codecov  # codecov executes coverage which needs to be in $PATH
    - pip install coveralls
    - coveralls

notifications:
    email: false

sudo: false

matrix:
    allow_failures:
        - python: nightly
