language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3
    - nightly
before_install:
    - pip uninstall setuptools -y
    - sudo apt-add-repository ppa:webupd8team/java -y
    - sudo apt-get update -y -qq 
    - sudo apt-get install openjdk-8-jre -y -qq 
install:
    - python bootstrap.py
    - ./bin/buildout install scripts crate test
script:
    - bin/coverage run bin/test
after_success:
    - PATH=$PATH:bin/ bin/codecov  # codecov executes coverage which needs to be in $PATH
notifications:
    email: false
sudo: required
dist: trusty
matrix:
    allow_failures:
        - python: nightly
