language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3
    - nightly
before_install:
    - pip install codecov
install:
    - pip uninstall setuptools -y
    - python bootstrap.py
    - ./bin/buildout install scripts crate test
script:
    - ./bin/test
after_success:
    - codecov
notifications:
    email: false
sudo: false
matrix:
    allow_failures:
        - python: nightly
