language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
install:
    - pip uninstall setuptools -y
    - python bootstrap.py
    - ./bin/buildout
script:
    - ./bin/test
notifications:
    email: false
